# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9aa22ecd1140e19cb06bd4537bb89d304d8375ddcabc2d1cc5dde843cdd93e80ef6eb01d5f0025d82e022b33d5b0084f4dcd6a74f77b170cef19e6472eb5cf

test:
  secret_key_base: 8272e9425a329fd7e0b8a7a5b06a97b104acaae84ec899e2e3430d23016bbfcc94627b689286f5f5774c906af4092a9f821a2d378058b72a2bb0e0042580169c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
